import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import './StartPage.css'; // Create this file for basic styling

function StartPage() {
  const navigate = useNavigate();
  const [username, setUsername] = useState<string>(''); // Added type annotation
  const [lobbyCode, setLobbyCode] = useState<string>(''); // Added type annotation
  const [errorMessage, setErrorMessage] = useState<string>(''); // Added type annotation

  const handleJoinLobby = () => {
    if (!username.trim() || !lobbyCode.trim()) {
      setErrorMessage("Username and Lobby Code are required to join.");
      return;
    }
    setErrorMessage('');
    console.log(`Attempting to join lobby: ${lobbyCode.trim().toUpperCase()} with username: ${username.trim()}`);
    // Navigate to the lobby page. Pass username via state.
    navigate(`/lobby/${lobbyCode.trim().toUpperCase()}`, { state: { username } });
  };

  const handleCreateLobby = () => {
    if (!username.trim()) {
      setErrorMessage("Username is required to create a lobby.");
      return;
    }
    setErrorMessage('');
    console.log(`Attempting to create lobby with username: ${username.trim()}`);
    // Navigate to a placeholder lobby page for now.
    // Replace 'NEW_LOBBY_ID' with the actual ID generated by your backend later.
    navigate(`/lobby/NEW_LOBBY_ID`, { state: { username } });
  };

  return (
    <div className="start-page-container">
      <h1>Laser Tag Treasure Hunt</h1>
      <div className="input-group">
        <label htmlFor="username">Username:</label>
        <input
          id="username"
          type="text"
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          placeholder="Enter your username"
          maxLength={15} // Limit username length
        />
      </div>

      <div className="input-group">
        <label htmlFor="lobbyCode">Lobby Code:</label>
        <input
          id="lobbyCode"
          type="text"
          value={lobbyCode}
          onChange={(e) => setLobbyCode(e.target.value.toUpperCase())} // Auto-uppercase lobby code
          placeholder="Enter lobby code"
          maxLength={6} // Common lobby code length
        />
      </div>

      {errorMessage && <p className="error-message">{errorMessage}</p>}

      <div className="button-group">
        <button onClick={handleJoinLobby}>
          Join Lobby
        </button>
        <button onClick={handleCreateLobby}>
          Create New Lobby
        </button>
      </div>

      <p className="note">
        Minimum 4 players required, up to 20 players. 
      </p>
    </div>
  );
}

export default StartPage;